<?php

namespace common\models;

use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%test}}".
 *
 * @property string $test_id
 * @property string $test_name
 * @property string|null $description
 * @property int|null $failCount
 * @property int|null $successCount
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property int|null $created_at
 * @property int|null $status
 * @property int|null $has_thumbnail
 *
 * @property User $createdBy
 */
class Test extends \yii\db\ActiveRecord
{

    const STATUS_UNLISTED =0;
    const STATUS_PUBLISHED =1;
    /** @var  UploadedFile*/
    public $thumbnailTest;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%test}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['test_id', 'test_name'], 'required'],
            [['description'], 'string'],
            [['failCount', 'successCount', 'created_by', 'updated_by', 'created_at', 'has_thumbnail'], 'integer'],
            [['test_id'], 'string', 'max' => 16],
            [['test_name'], 'string', 'max' => 255],
            [['test_id'], 'unique'],
            ['has_thumbnail', 'default', 'value' => 0],
            ['thumbnailTest', 'image', 'minWidth' => 150],
            ['status', 'default', 'value' => self::STATUS_UNLISTED],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'test_id' => 'Test ID',
            'test_name' => 'Test Name',
            'description' => 'Description',
            'failCount' => 'Fail Count',
            'successCount' => 'Success Count',
            'created_by' => 'Created By',
            'status' => 'Статус',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'has_thumbnail' => 'Картинка',
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\UserQuery
     */
    public function getCreatedBy()
    {

        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\TestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\TestQuery(get_called_class());
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $isInsert= $this->isNewRecord;
        if($isInsert){
            $this->test_id = Yii::$app->security->generateRandomString(8);
        }

        if($this->thumbnailTest){
            $this->has_thumbnail = 1;
        }

        $saved = parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        if (!$saved){
            return false;
        }

        if($this->thumbnailTest)
        {
            $thumbnailTestPath = Yii::getAlias('@frontend/web/storage/test/thumbs'.$this->test_id.'.jpg');
            if(!is_dir(dirname($thumbnailTestPath))){
                FileHelper::createDirectory(dirname($thumbnailTestPath));
            }
            $this->thumbnailTest->saveAs($thumbnailTestPath);
        }

        return true;
    }

    public function getThumbnailTestLink()
    {
        return $this->has_thumbnail ?
            Yii::$app->params['frontendUrl'].'storage/test/thumbs/'.$this->test_id.'.jpg' : '';
    }
}
